In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

In [2]:
ab = []                        

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

Daha fazla liste/vektör çarpmak istersek veye matrisler üzerinde işlem yapmak istersek her seferinde bu kadar karmaşık işlem yapmak zorunda mıyız? İşte NumPy burada yüksek seviye özelliği ile araya girip bize çok kolay bir imkan sağlamaktadır.

In [4]:
import numpy as np
#import dış modülleri/kütüphaneleri programda kullanabilmek adına içeriye dahil etmek için kullanılır.
#numpy kütüphanesini np kısa yolu ile programımıza çağırdık.

In [5]:
a = np.array([1,2,3,4]) #numpy kütüphanesi içerisinden array isimli bir fonksiyon çağırdık. Bu fonksiyon numpy array'i oluşturmaya yarar.
b = np.array([2,3,4,5])

In [6]:
a * b

array([ 2,  6, 12, 20])

Anlaşılacağı üzere biz numpy'ı daha üst seviyeden daha az çabayla daha büyük işler yapabilme olanağı sağladığından dolayı kullanıyor olacağız. Yer tutma maaliyetlerini de numpy çok azaltmaktadır. Örneğin liste içerisinde 4 integer tip var. Liste içindeki her tip için bu integer'dır bilgisi tutulurken, numpy arrayi içerisindeki 4 eleman için tek tip bilgisi tutulur, bunların hepsi integerdır bilgisi.

# NumPy Array'i Oluşturmak
NumPy arrayi NumPy kütüphanesi içerisinde yer alan tıpkı listeler gibi sözlükler gibi bir veri tipidir.
Numpy arraylerini, listeler veya farklı veri tipleri üzerinden oluşturabiliriz.

# Liste üzerinden NumPy array oluşturma

In [1]:
import numpy as np

In [7]:
np.array([1,2,3,4,5]) #ilk yöntem numpy içerisinde yer alan array fonksiyonudur. İçerisine liste alır. Liste üzerinden array oluşturulmuş olur.

array([1, 2, 3, 4, 5])

In [8]:
a = np.array([1,2,3,4,5])

In [9]:
type(a) #tipine bakalım

numpy.ndarray

In [10]:
np.array([3.14, 4, 2, 13]) #NumPy'ın sabit tip baskısı vardır, veri saklama maliyetinden kurtarır. 

array([ 3.14,  4.  ,  2.  , 13.  ])

In [11]:
np.array([3.14, 4, 2, 13], dtype = "int") #içerisinde sabit tek tip veri tutulur. dtype argümanı ile hepsi integer olsun diyoruz

array([ 3,  4,  2, 13])

# Sifirdan array olusturma 

In [12]:
np.zeros(10, dtype = int) #10 tane 0'lardan oluşan bir array oluştu.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5), dtype = int) #1'lerden oluşan array/matris oluşturuldu

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full((3,5), 3) #belirli bir sayıdan oluşan bizim verdiğimiz boyut bilgisi ile bir matris 2 boyutlu array oluşturmuş olduk

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [67]:
np.arange(0,31,3) #***doğrusal bir dizi oluşturma. 0'dan 31'e kadar 3'er 3'er artacak elemanlardan oluşur. İki boyutlu dizi oluşturmada kullanılmaz. Ancak oluşturulan array istenirse daha sonra reshape ile iki boyutlu hale getirilebilir.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
np.arange(31)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [17]:
np.linspace(0,1,10) #iki değer arasında (örneğin 0 ile 1 ) arasında belirli sayıda değer oluştur. Bu örnek için 10 tane

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
#Dağılımını kendimizin belirleyeceği bir array oluşturmak istiyorsak;

In [18]:
np.random.normal(10, 4, (3,4)) #***örneğin ortalaması 10, std'si 4 yani istediğimiz dağılıma sahip olacak arrayler oluşturabiliyoruz.

array([[ 7.25642116, 16.13661285, 12.47351985,  9.891052  ],
       [ 5.54954316,  7.81922783,  9.70964379, 11.20590446],
       [18.0654704 , 10.14777782,  5.29329354,  7.71056735]])

In [19]:
np.random.randint(0,10, size=(3,3)) #***Dağılımla ilgilenmeyip 0 ile 10 arasında integer rastgele değerlerden veri oluşturmak için kullanılır.

array([[9, 5, 6],
       [2, 1, 2],
       [2, 2, 7]])

# Özellikleri

* **ndim**: _boyut sayısı_
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array içerisindeki elemanların veri tipi

Bu ifadeleri kullanarak numpy array'inin özelliklerine erişmiş oluyoruz.

In [20]:
import numpy as np

In [21]:
np.random.randint(10, size = 10)# 0'dan 10'a olacak şekilde rastgele 10 tane sayı oluşturdu. Başlangıç değerini 0 olarak kendisi atadı.

array([8, 2, 8, 3, 7, 1, 7, 5, 8, 1])

In [22]:
a = np.random.randint(10, size = 10)

In [23]:
a.ndim #array boyutunu döndürür. Tek boyutlu bir arraydir.

1

In [25]:
a.shape #boyut bilgisi döndürür.Elimizdeki array tek boyutlu olduğu için bir boyutunun bilgisi döner, sadece 10 bilgisini döndürdü.

(10,)

In [26]:
a.size #array içindeki toplam eleman sayısını bize verdi

10

In [26]:
a.dtype # İçerisindeki integer'ın tipini verir

dtype('int32')

In [27]:
b = np.random.randint(10, size = (3,5)) #0'dan 10'a kadar 3,5 boyutunsa rastgele değerlerden oluşan matris oluşturdu

In [28]:
b

array([[8, 1, 5, 8, 9],
       [3, 8, 4, 9, 9],
       [8, 9, 8, 9, 5]])

In [29]:
b.ndim #kaç boyutlu olduğu bilgisini verir

2

In [30]:
b.shape #boyutlarının tek tek bilgilerini verir

(3, 5)

In [31]:
b.size #içerisindeki toplam eleman sayısını verir

15

In [32]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme (Reshaping)

In [38]:
#Bazen çalışmalarda modeller girdi olarak belirli bir boyut isteyebiliyor ve limizdeki çıktı o boyuta uymayabiliyor. Bu durumda yeniden boyutlandırma yapmamız gerekebilir.

In [33]:
import numpy as np

In [35]:
np.arange(1,10) #1'den 10'a kadar olan sayılardan oluşan bir array oluşturalım

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(1,10).reshape((3,3)) #Bu array'in boyutunu 3,3 olacak şekilde değiştirelim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a = np.arange(1,10)

In [39]:
a
#çıktıya bakacak olursak tek [] vardır. Bu onun vektör olduğu (tek boyutlu array) anlamına gelir.
#Tek boyutlu array vektör, iki boyutlu array yani matris olarak isimlendirilir.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a.ndim

1

In [41]:
b = a.reshape((1,9))#tek boyutlu arrayi bazı işlemler için matris formuna dönüştürmek gerebilir.Ancak tek boyut bilgisi yine aynı kalsın istiyorsak, bir boyutunu 1 yaparak bu işlemi yaopabiliriz.

In [43]:
b
##çıktıya bakacak olursak 2 tane [] vardır. Bu onun matris olduğu (iki boyutlu array) anlamına gelir.

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [44]:
b.ndim # 1 satır 9 sütundan oluşur.

2

In [45]:
b.shape

(1, 9)

# Array Birlestirme (Concatenation)

In [46]:
import numpy as np

In [48]:
x = np.array([1,2,3]) #liste yardımıyla numpy arrayi oluşturduk
y = np.array([4,5,6])

In [49]:
np.concatenate([x, y]) #2 arrayi birleştirir

array([1, 2, 3, 4, 5, 6])

In [50]:
z = np.array([7,8,9])

In [51]:
np.concatenate([x, y, z]) # 3 arrayi birleştirdi

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
#iki boyut

In [53]:
a = np.array([[1,2,3], #elle 2 boyultu array oluşturduk
              [4,5,6]])

In [54]:
np.concatenate([a,a]) #2 adet 2 boyutlu arrayi birleştirir.

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [55]:
np.concatenate([a,a], axis = 1) #sütun bazında birleştirdi. axis eksen belirtmek için kullanılır. 0 satrıları 1 sütunları belirtir. ön tanımlı değeri 0'dır.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [56]:
import numpy as np

In [57]:
x = np.array([1,2,3,99,99,3,2,1]) #Örneğin 3 parçaya ayırmak isteyelim

In [58]:
np.split(x, [3,5]) #split ile  x'i ayır. 3. indise kadar böl daha sonra 5. indise kadar böl. n indekse karşılık n+1 bölüme ayrılıyor

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [59]:
a,b,c = np.split(x, [3,5]) #ayırdıklarımızın her birini bir değişkene ata ki sonra kullanabileyim.

In [60]:
a

array([1, 2, 3])

In [61]:
b

array([99, 99])

In [62]:
c

array([3, 2, 1])

In [63]:
#iki boyutlu ayırma

In [68]:
m = np.arange(16).reshape(4,4) #0'dan 16'ya kadar array oluştur ve  4,4 boyutlarında bir matrise dönüştür.
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
np.vsplit(m, [2]) #ikinci satırdan sonraki kısmı böler

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [71]:
ust, alt = np.vsplit(m, [2])#böldüğün arrayi üst ve alt değişkenlerine ayır

In [72]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [73]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
np.hsplit(m, [2]) # 2'ya kdar dikey olarak böler.

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [76]:
sag, sol = np.hsplit(m, [2]) #ayrılan arrayleri sağ ve sol değişkenlerine atadık.

In [77]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [78]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [79]:
import numpy as np

In [80]:
v = np.array([2,1,4,3,5]) #numpy array oluşturuyoruz.

In [81]:
v

array([2, 1, 4, 3, 5])

In [82]:
np.sort(v) #küçükten büyüğe sıralar. v arrayinin orjinal yapısını bozmaz.Sıralı halini kullanmak istiyorsak bir değişkene atayabiliriz.

array([1, 2, 3, 4, 5])

In [83]:
v

array([2, 1, 4, 3, 5])

In [84]:
v.sort() #OOP mantığına göre sort yapıldı fakat arrayin orjinalini değiştirdi.

In [85]:
v

array([1, 2, 3, 4, 5])

In [86]:
#iki boyutlu array siralama

In [87]:
m = np.random.normal(20,5, (3,3)) # 2 boyutlu array oluşturalım. Ortalaması 20, std'si 5 olacak array oluşturduk.

In [88]:
m

array([[16.15273157, 14.39930733, 22.60934061],
       [27.65689078, 17.24572256, 21.27185391],
       [22.43669329, 28.09608591, 16.6980948 ]])

In [89]:
np.sort(m, axis = 1) #İki boyutlu arrayin satırları kendi içinde küçükten büyüğe olacak şekilde sıralandı.

array([[14.39930733, 16.15273157, 22.60934061],
       [17.24572256, 21.27185391, 27.65689078],
       [16.6980948 , 22.43669329, 28.09608591]])

In [90]:
np.sort(m, axis = 0) #İki boyutlu arrayin sütunları kendi içinde küçükten büyüğe olacak şekilde sıralandı.

array([[16.15273157, 14.39930733, 16.6980948 ],
       [22.43669329, 17.24572256, 21.27185391],
       [27.65689078, 28.09608591, 22.60934061]])

# Index ile Elemanlara Erişmek

In [91]:
import numpy as np
a = np.random.randint(10, size = 10) #tek boyutlu 0 dan 10'a kadar rastgele 10 elemandan oluşan array 
a

array([8, 9, 0, 6, 5, 1, 7, 9, 7, 8])

In [92]:
a[0] #Bilindiği üzere nesnenin ismi ve [indeks] ile istediğimiz elemana ulaşabiliriz.

8

In [93]:
a[-1] #veriye tersten erişim. tersten 1. eleman

8

In [94]:
a[0] = 100 #erişilen veride değişiklik yapmak

In [95]:
a

array([100,   9,   0,   6,   5,   1,   7,   9,   7,   8])

In [96]:
m = np.random.randint(10, size = (3,5))
m

array([[8, 8, 0, 7, 3],
       [1, 7, 9, 3, 0],
       [8, 4, 8, 7, 1]])

In [97]:
m[0,0] #0. satır 0. sütundaki değere erişir

8

In [98]:
m[1,1]

7

In [99]:
m[1, 4]

0

In [100]:
m[1, 4] = 99 #1. satır 4. sütundaki değeri 99 ile değiştir.

In [101]:
m

array([[ 8,  8,  0,  7,  3],
       [ 1,  7,  9,  3, 99],
       [ 8,  4,  8,  7,  1]])

In [103]:
m[1,4] = 2.2

In [104]:
m #sabit tip veri içerdiği için sadece tam kısmını aldı çünkü içeride integer tipi veri içeriyor biz dışarıdan noktalı sayı eklemeye çalışıyoruz kabul etmez onu da içerisindekilerin formatına dönüştürür

array([[8, 8, 0, 7, 3],
       [1, 7, 9, 3, 2],
       [8, 4, 8, 7, 1]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [105]:
import numpy as np

In [106]:
a = np.arange(20,30) #20 ile 30 arasındaki elemanlardan oluşmuş tek boyutlu array oluşturduk.
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [107]:
a[0:3] #slice : ifadesidir. 0'dan 3'e kadar olan indekslerdeki elemanları seç

array([20, 21, 22])

In [108]:
a[:3] #0'dan 3'e kadar olan indekslerdeki elemanları seç

array([20, 21, 22])

In [109]:
a[3:] #3'ten sona kadar git

array([23, 24, 25, 26, 27, 28, 29])

In [110]:
a[1::2] #1. indeksten itibaren 2'şer 2'şer artacak şekilde elemanları yazdı

array([21, 23, 25, 27, 29])

In [111]:
a[0::2] #0. indeksten itibaren 2'şer 2'şer artacak şekilde elemanları yazdı

array([20, 22, 24, 26, 28])

In [112]:
a[2::2]

array([22, 24, 26, 28])

In [113]:
a[0::3]

array([20, 23, 26, 29])

In [114]:
#iki boyutlu slice islemleri

In [115]:
m = np.random.randint(10, size = (5,5)) #0'dan 10'a kadar elemanlardan oluşan 5,5 boyutunda array oluşturduk

In [116]:
m

array([[1, 7, 4, 4, 5],
       [1, 7, 8, 5, 9],
       [3, 4, 8, 5, 0],
       [0, 6, 0, 7, 0],
       [7, 8, 8, 1, 5]])

In [117]:
m[:,0] #bütün satırları seç, 0. sütunu seç

array([1, 1, 3, 0, 7])

In [118]:
m[:,1] ##bütün satırları seç, 1. sütunu seç

array([7, 7, 4, 6, 8])

In [119]:
m[:,4]#bütün satırları seç, 4. sütunu seç

array([5, 9, 0, 0, 5])

In [120]:
m

array([[1, 7, 4, 4, 5],
       [1, 7, 8, 5, 9],
       [3, 4, 8, 5, 0],
       [0, 6, 0, 7, 0],
       [7, 8, 8, 1, 5]])

In [121]:
m[0,:] #0. satırı seç, tüm sütunları seç

array([1, 7, 4, 4, 5])

In [122]:
m[0] #yine 0. satır tüm sütunlar seçilir

array([1, 7, 4, 4, 5])

In [123]:
m[1,:] #1. satırı seç, tüm sütunları seç

array([1, 7, 8, 5, 9])

In [124]:
m[0:2, 0:3] #0'dan 2'ye kadar satırları al, 0'dan 3'e kadar sütunları al

array([[1, 7, 4],
       [1, 7, 8]])

In [125]:
m[:,0:2] #bütün satrıları al, 0'dan 2'ye kadar sütunları al

array([[1, 7],
       [1, 7],
       [3, 4],
       [0, 6],
       [7, 8]])

In [126]:
m

array([[1, 7, 4, 4, 5],
       [1, 7, 8, 5, 9],
       [3, 4, 8, 5, 0],
       [0, 6, 0, 7, 0],
       [7, 8, 8, 1, 5]])

In [127]:
m[1:3, 0:2] #1'den 3'e kadar satırları al, 0'dan 2'ye kadar sütunları al

array([[1, 7],
       [3, 4]])

# Alt Küme Üzerinde İşlem Yapmak

In [128]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[5, 2, 9, 7, 7],
       [8, 4, 0, 5, 8],
       [0, 9, 9, 3, 4],
       [5, 9, 7, 7, 5],
       [9, 8, 2, 7, 9]])

In [129]:
alt_a = a[0:3, 0:2] #0'dan 3'e kadar satırları al ve 0'dan 2'ye kadar sütunları al.
alt_a

array([[5, 2],
       [8, 4],
       [0, 9]])

In [130]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [131]:
alt_a

array([[99999,     2],
       [    8,   888],
       [    0,     9]])

In [132]:
a #görüldüğü üzere alt küme üzerinde yaptığımız işlemler ana arrayi etkiledi değiştirdi

array([[99999,     2,     9,     7,     7],
       [    8,   888,     0,     5,     8],
       [    0,     9,     9,     3,     4],
       [    5,     9,     7,     7,     5],
       [    9,     8,     2,     7,     9]])

In [133]:
m = np.random.randint(10, size = (5, 5))
m

array([[6, 7, 4, 4, 3],
       [1, 8, 3, 4, 2],
       [2, 8, 6, 8, 3],
       [3, 7, 1, 3, 1],
       [4, 0, 2, 7, 4]])

In [134]:
alt_b = m[0:3, 0:2].copy() #ana arrayi etkilememek için copy() metodunu kullanacağız. Seçmiş olacağı alt kümeyi ana arrayden bağımsızlaştırır.
alt_b

array([[6, 7],
       [1, 8],
       [2, 8]])

In [135]:
alt_b[0,0] = 9999

In [136]:
alt_b

array([[9999,    7],
       [   1,    8],
       [   2,    8]])

In [137]:
m #copy ile alt küme seçtiğimizde, alt küme üzerinde yaptığımız işlemler görüldüğü üzere ana arrayi etkilemedi.

array([[6, 7, 4, 4, 3],
       [1, 8, 3, 4, 2],
       [2, 8, 6, 8, 3],
       [3, 7, 1, 3, 1],
       [4, 0, 2, 7, 4]])

# Fancy Index ile Elemanlara Erişmek
Fancy hem NumPy arraylerinde hemde ileride göreceğimiz Pandas dataframe'lerinde daha ileri düzey eleman seçme imkanı vermektedir.
Fancy'nin arka plandaki mantığını anlamaya çalışacağız.

In [138]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [139]:
v[1]

3

In [140]:
v[3]

9

In [141]:
v[5]

15

In [142]:
[v[1], v[3], v[5]] #çektiklerimizi bir arada görmek istiyoruz

[3, 9, 15]

In [146]:
al_getir = [1,3,5] # elimizdeki indekslere ait verilerin hepsini getirmek istiyoruz yukarıdaki gibi tek tek getirmeden
                   #indeks sorgulama işlemini tek seferde nasıl  yapıyoruz sorusunun cevabı fancy indeks'tir.

In [147]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [148]:
v[al_getir] # v arrayindeki al_getir arrayindeki indekslere denk gelen elemanları getir.İşte bu fancy işlemidir.

array([ 3,  9, 15])

In [149]:
#iki boyutta fancy

In [150]:
m = np.arange(9).reshape((3,3)) 

In [151]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [152]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [145]:
satir

array([0, 1])

In [153]:
m[satir, sutun] #tuttuğu indekslerdeki elemanları getirdi m[ [0,1], [1,2])]. İlk köşeli parantezdekiler satır ikincidekiler sütun. Yani sonuç: 0. satır  1. sütun, 1. satır 2. sütun olacak

array([1, 5])

In [154]:
#basit index ile fancy index

In [155]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [156]:
m[0, [1,2]] #fancy ile basit indeksi bir arada kullanıldık. 0. satır 1. sütun, 0. satır 2. sütun

array([1, 2])

In [157]:
#slice ile fancy

In [158]:
m[0:, [1,2]] #0. satırda itibaren tüm satırları al, 1. ve 2. sütunları al

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri
Belirli bir arrayin içerisinde bir koşulu çağırıp, bu koşulu sağlayan elemanların yakalanması işlemi.

In [159]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [160]:
v < 3 # v arrayin içerisindeki değerlerin 3'ten küçük olup olmadığını her bir eleman için sorgulayalım

array([ True,  True, False, False, False])

In [161]:
v[v < 3] #fancy indeks devreye giriyor. 3'ten küçük olanlara eriş demek istiyoruz.

array([1, 2])

In [162]:
v[v > 3]

array([4, 5])

In [163]:
v[v >= 3]

array([3, 4, 5])

In [164]:
v[v <= 3]

array([1, 2, 3])

In [165]:
v[v == 3]

array([3])

In [166]:
v[v != 3]

array([1, 2, 4, 5])

# Matematiksel İşlemler

In [167]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [168]:
v - 1 #elemanlardan 1 çıkar

array([0, 1, 2, 3, 4])

In [169]:
v * 5 #elemanların hepsini 5 ile çarp

array([ 5, 10, 15, 20, 25])

In [170]:
v / 5 ##elemanların hepsini 5'e böl

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [171]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

Şu ana kadar matematiksel operatörler ile işlemlerimizi gerçekleştirdik.

In [172]:
#aslında biz operatörleri kullansak da numpy içerisinde bulunan fonksiyonlar kullanılıyor.

In [173]:
v = np.array([1, 2, 3, 4, 5])

In [174]:
np.subtract(v, 1) #v vektöründen 1'i çıkar

array([0, 1, 2, 3, 4])

In [175]:
np.add(v, 1)#v vektöründeki her elemana 1 ekle demektir.

array([2, 3, 4, 5, 6])

In [176]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [177]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [178]:
v**2

array([ 1,  4,  9, 16, 25])

In [179]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [180]:
np.power(v, 3) #üs alma. 3. dereceden üs al demektir.

array([  1,   8,  27,  64, 125], dtype=int32)

In [181]:
v % 2 #2'ye bölümünden kalanları getir demektir.

array([1, 0, 1, 0, 1], dtype=int32)

In [182]:
np.mod(v, 2) #% operatörünün fonksiyon karşılığı mod fonksiyonudur.

array([1, 0, 1, 0, 1], dtype=int32)

In [183]:
np.absolute(np.array([-3])) #absolute fonksiyonu mutlak değerini alır.

array([3])

In [184]:
np.sin(360) # trigonometrik işlemleri gerçekleştirir. Sinüs alma işlemi

0.9589157234143065

In [185]:
np.cos(180)

-0.5984600690578581

In [186]:
v = np.array([1,2,3])

In [187]:
np.log2(v) #logaritma tabanı değiştirilebilir. 2 tabanında log

array([0.       , 1.       , 1.5849625])

In [188]:
np.log10(v) #10 tabanında logaritmasını al

array([0.        , 0.30103   , 0.47712125])

In [189]:
?np 
#numpy ile ilgili genel bilgileri verir. Buradan erişebileceklerimize erişebiliriz. Yada google üzerinden numpy trigonometrik fonksiyonların ingilizcesini aratırsak kolayca erişebiliriz.

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Fatma Zehra\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\fatma zehra\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> 

In [ ]:
#cheatsheet
#numpy mathematics cheat sheet ile google'dan arama yapabiliriz.

# İstatistiksel Hesaplamalar
İstatistik işlemleri öğrenmek için de numpy statistics cheat sheet yazarak googledan aratabiliriz.

In [190]:
v

array([1, 2, 3])

In [191]:
np.mean(v) #v vektörü elemanlarının ortalaması

2.0

In [192]:
v.sum()

6

In [193]:
v.min()

1

* np.mean(arr,axis=0) | Returns mean along specific axis

* arr.sum() | Returns sum of arr

* arr.min() | Returns minimum value of arr

* arr.max(axis=0) | Returns maximum value of specific axis

* np.var(arr) | Returns the variance of array

* np.std(arr,axis=1) | Returns the standard deviation of specific axis

* arr.corrcoef() | Returns correlation coefficient of array

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [194]:
import numpy as np

**5 * x0 + x1 = 12  
x0 + 3 * x1 = 10**

In [195]:
#Numpy'ın anlayacağı hale getirmemiz gerekiyor. Bunun yolu da katsayıları ve sonuçları birer listeye koymaktır.

In [196]:
a = np.array([[5,1], [1,3]]) #bilinmeyenlerin katsayısı arraylar ile ifade edildi.
b = np.array([12,10]) #oluşan değerler ayrı bir arraya koyulur.

In [197]:
a

array([[5, 1],
       [1, 3]])

In [198]:
b

array([12, 10])

In [200]:
x = np.linalg.solve(a, b)#numpy içerisinden lineer cebir işlemleri için özelleştirilmiş linalg alt paketinden solve fonksiyonunu çağırıyoruz.
                         #Diyoruz ki sen girmiş olduğum 1. argüman ve 2. argüman arasındaki ilişki içerisinde bu oluşacak katsayıları hesapla.
x

array([1.85714286, 2.71428571])

# BOLUM SONU DEGERLENDIRMESI

# Pandas Serisi Oluşturmak
Pandas içerisinde yer alan bir veri tipidir. Tek boyutlu bir array olarak düşünebiliriz. NumPy arraylerinden farklı olarak bir de indeks bilgisi tutulmaktadır.

In [210]:
import pandas as pd #pandas kütüphanesini import ettik pd olarak isim verdik

In [211]:
pd.Series([10,88,3,4,5]) #Liste üzerinden bir pandas serisi oluşturduk.
#Çalıştırdığımızda ilk sütunda gördüklerimiz serinin indeksleridir diğer sütunda gördüklerimiz ise veri değerleridir.
#Değerleri indeksleri ile birlikte tutar.

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [212]:
seri = pd.Series([10,88,3,4,5])

In [213]:
type(seri) #seri tipini görelim

pandas.core.series.Series

In [214]:
seri.axes #Bu veri tipinin indeks bilgilerine erişebiliyoruz.Çalıştığında 0'dan 5'e kadar gittiği bilgisini görüyoruz.

[RangeIndex(start=0, stop=5, step=1)]

In [215]:
seri.index

RangeIndex(start=0, stop=5, step=1)

In [217]:
seri.values #içerisindeki sadece değerleri verir, indeksleri vermez

array([10, 88,  3,  4,  5], dtype=int64)

In [207]:
seri.dtype #seri içerisindeki değerlerle ilgili bilgi verir

dtype('int64')

In [208]:
seri.size #içerisindeki eleman sayısını verir.

5

In [209]:
seri.ndim #Tek boyutlu array olduğu için 1 cevabını verir

1

In [214]:
seri.head(3)# elimizdeki serinin ilk 3 vb. gözlemine erişmek için kullanabiliriz.

0    10
1    88
2     3
dtype: int64

In [215]:
seri.tail(3)#  son 3 vb. elemanlarını verir.

2    3
3    4
4    5
dtype: int64

In [216]:
#index isimlendirmesi

In [218]:
pd.Series([99,22,332,94,5]) #seri oluşturduk

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [219]:
pd.Series([99,22,332,94,5], index = [1,3,5,7,9]) #indeks isimlerini değiştirdik

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [220]:
pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [221]:
seri = pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"]) 

In [222]:
seri["a"] # a isimli indekse ait karşılan gelen değere ulaşırız

99

In [223]:
seri["a":"c"] #slice şeklinde de yazılabilir. a'dan c'ya kadar olan indeksleri yaz

a     99
b     22
c    332
dtype: int64

In [234]:
#Pandas slicing işleminde, indeks numaraları veya etiketleri arasında farklılıklar vardır. İndeks numaraları, sıfırdan başlayarak artan tam sayılar olarak atanırken, etiketler kullanıcı tarafından tanımlanır ve herhangi bir veri türüne sahip olabilir.

#Bu nedenle, "a":"c" dilimlemesi etiketler üzerinden yapılır ve "c" de dahil edilir. Bununla birlikte, "0:2" kullanılarak numaralarla dilimleme yaparsanız, son indeks (2) dahil edilmez ve yalnızca 0 ve 1 indeksleri alınır.

In [224]:
#sozluk uzerinden seri olusturmak

In [225]:
sozluk = {"reg":10, "log":11, "cart": 12}

In [226]:
seri = pd.Series(sozluk) #sözlüğün key değeri indeks , value değeri de serinin değeri olur.

In [227]:
seri

reg     10
log     11
cart    12
dtype: int64

In [228]:
seri["reg":"cart"]

reg     10
log     11
cart    12
dtype: int64

In [229]:
#iki seriyi birlestirerek seri olusturma

In [243]:
pd.concat([seri,seri]) #concat isimli fonksiyon iki seriyi alt alta birleştirir.

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

# Eleman İşlemleri

In [4]:
import numpy as np
a = np.array([1,2,33,444,75])
seri = pd.Series(a) #seriyi numpy array üzerinden de oluşturabiliriz.
seri

NameError: name 'pd' is not defined

In [233]:
seri[0]

1

In [234]:
seri[0:3] #0'dan 3'e kadar olan elemanları ver

0     1
1     2
2    33
dtype: int32

In [235]:
seri = pd.Series([121,200,150,99], 
                 index = ["reg","loj","cart","rf"]) #indeks isimlerini kendimizin verdiği seri oluşturduk

In [236]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [237]:
seri.index #sadece indeks değerlerine erişiriz

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [238]:
seri.axes

[Index(['reg', 'loj', 'cart', 'rf'], dtype='object')]

In [239]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [240]:
list(seri.items()) #her bir key değerine karşılık gelen value değerii vermiş (key, value) şeklinde getirir

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [241]:
seri.values #serinin sadecedeğerlerine erişiriz

array([121, 200, 150,  99], dtype=int64)

In [242]:
#eleman sorgulama

In [243]:
"reg" in seri #reg ifadesi seri içerisinde mi? içindeyse true, değilse false değeri döner

True

In [244]:
"a" in seri

False

In [245]:
seri["reg"]

121

In [246]:
#fancy eleman

In [247]:
seri[["rf", "reg"]] #iki köşeli parantez girilir

rf      99
reg    121
dtype: int64

In [248]:
seri["reg"] = 130 #reg ifadesinin değerini değiştirebiliriz.

In [2]:
seri["reg"]

NameError: name 'seri' is not defined

In [3]:
seri["reg":"cart"] #slice yapabiliriz. reg key değerinden cart'a kadar demek

NameError: name 'seri' is not defined

# Pandas DataFrame Oluşturma
Yapısal bir veri tipidir. Excel yapısına benzer. NumPy'dan farklı olarak içerisinde farklı tip verileri tutabilir.
Pandas dataframe yapılarını makine öğrenmesi modellerine vereceğimiz veri setleri olarak düşünebiliriz.(DataFrame ->birden fazla veri tipi)

In [251]:
import pandas as pd

In [5]:
l = [1,2,39,67,90] #liste üzerinden oluşturalım

In [6]:
l

[1, 2, 39, 67, 90]

In [254]:
pd.DataFrame(l, columns = ["degisken_ismi"]) # ilk argümana listeyi belirtiyoruz ve ayrıca bu listeye değişken ismi şeklinde bir isim veriyoruz

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [255]:
a = np.array([1,2,3,4,5])

In [256]:
pd.DataFrame(a, columns = ["deg1"]) #numpy array üzerinden dataframe oluşturduk

deg1
0     1
1     2
2     3
3     4
4     5

In [257]:
import numpy as np
m = np.arange(1,10).reshape((3,3)) # 3,3 boyutlu 1'den 10'a kadar sayılardan oluşan array oluşturalım.
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [258]:
pd.DataFrame(m, columns = ["var1","var2","var3"]) #ilk argümanımız numpy array, sonra columns ile değişkenleri aralarına virgül koyarak isimlendiriyoruz.

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

## Dataframeler bizim için veri bilimi ve yapay zeka alanında en çok kullanılan yapıdır. Bu nedenle bizim için kilit rolü oynar iyi anlamalıyız.

In [259]:
#df isimlendirme

In [262]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df.head() #varsayılan değeri 5'tir

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [263]:
df.columns = ("deg1","deg2","deg3") #değişkenlerin isimlerini değiştirme

In [264]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [265]:
type(df)

pandas.core.frame.DataFrame

In [266]:
df.axes #satır ve sütun bilgilerini verir

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [267]:
df.shape #boyut bilgisini (satır ve sütun sayısı) verir

(3, 3)

In [268]:
df.ndim #kaç boyutlu olduğu bilgisini verir

2

In [269]:
df.size #eleman sayısını verir

9

In [270]:
df.values #sadece değerleri çeker ve bunu numpy array nesnesi olarak çeker

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [271]:
type(df.values)

numpy.ndarray

In [272]:
df.head() #baştan gözlemlere erişmek

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [273]:
df.tail(1) #sondan gözlemlere erişmek

deg1  deg2  deg3
2     7     8     9

# Eleman İşlemleri

In [309]:
import numpy as np
s1 = np.random.randint(10, size = 5) #0'dan 10'a kadar olan değerlerden 5 elemanlı numpy array oluştur
s2 = np.random.randint(10, size = 5) #0'dan 10'a kadar olan değerlerden 5 elemanlı numpy array oluştur
s3 = np.random.randint(10, size = 5) #0'dan 10'a kadar olan değerlerden 5 elemanlı numpy array oluştur

In [310]:
sozluk = {"var1": s1, "var2": s2, "var3": s3} #numpy arraylari üzerinden sözlük oluştur

In [311]:
sozluk

{'var1': array([8, 0, 4, 3, 9]),
 'var2': array([3, 3, 0, 1, 6]),
 'var3': array([4, 2, 3, 9, 7])}

In [312]:
df = pd.DataFrame(sozluk) #sözlük üzerinden dataframe oluştur. Key değeleri sütun(değişken) isimlerini oluşturur.

In [313]:
df

var1  var2  var3
0     8     3     4
1     0     3     2
2     4     0     3
3     3     1     9
4     9     6     7

In [314]:
df[0:1] #0'dan 1'e kadar

var1  var2  var3
0     8     3     4

In [315]:
df.index #0'dan 5'e kadar indeksler 1'er artıyor

RangeIndex(start=0, stop=5, step=1)

In [316]:
df.index = ["a","b","c","d","e"] #indeks isimlerini değiştirdik.

In [317]:
df

var1  var2  var3
a     8     3     4
b     0     3     2
c     4     0     3
d     3     1     9
e     9     6     7

In [319]:
df["c":"e"] #slice ile c'den e'ye kadar 

var1  var2  var3
c     4     0     3
d     3     1     9
e     9     6     7

In [284]:
#silme

In [285]:
df.drop("a", axis = 0) # a indeks satırını (gözlemi) sil. axis=0 olduğu için satır bazında siler

var1  var2  var3
b     7     8     8
c     2     5     8
d     5     0     6
e     5     1     1

In [286]:
df #silmeden sonra dateframe üzerinde kalıcı değişiklik olmadı

var1  var2  var3
a     0     0     6
b     7     8     8
c     2     5     8
d     5     0     6
e     5     1     1

In [287]:
df.drop("a", axis = 0, inplace = True) #inplace=true argümanı dataframe üzerinde yapılan değişikliğin kalıcı olmasını sağlar.

In [288]:
df

var1  var2  var3
b     7     8     8
c     2     5     8
d     5     0     6
e     5     1     1

In [289]:
#fancy 

In [290]:
l = ["c","e"]

In [291]:
df.drop(l, axis = 0) #c ve e satırlarını silme işlemini ayrı ayrı yazmaktansa fancy ile yapıyoruz. axis=0 satırlara göre sil demek.

var1  var2  var3
b     7     8     8
d     5     0     6

In [292]:
#degiskenler (sütunlar) icin

In [293]:
df

var1  var2  var3
b     7     8     8
c     2     5     8
d     5     0     6
e     5     1     1

In [294]:
"var1" in df #var1 isimli değişken bu dataframe içerisinde var mı diyoruz.

True

In [295]:
l = ["var1","var4","var2"] #liste oluşturalım

In [296]:
for i in l: #bu değişkenler bu dataframe içerisinde var mı?
    print(i in df)

True
False
True


In [297]:
df

var1  var2  var3
b     7     8     8
c     2     5     8
d     5     0     6
e     5     1     1

In [298]:
df["var1"]

b    7
c    2
d    5
e    5
Name: var1, dtype: int32

In [299]:
df["var4"] = df["var1"] / df["var2"] #var4 isimli değişken oluştur ve ona var1 değişken ve var2 değişkeni kullanarak değer ata.

In [300]:
df

var1  var2  var3   var4
b     7     8     8  0.875
c     2     5     8  0.400
d     5     0     6    inf
e     5     1     1  5.000

In [301]:
#degisken silmek

In [302]:
df.drop("var4", axis = 1) #var4 değişkenini sütuna göre sil (axis=1 olduğu için)

var1  var2  var3
b     7     8     8
c     2     5     8
d     5     0     6
e     5     1     1

In [303]:
df

var1  var2  var3   var4
b     7     8     8  0.875
c     2     5     8  0.400
d     5     0     6    inf
e     5     1     1  5.000

In [304]:
df.drop("var4", axis = 1, inplace = True) #var4 silme işlemini verisetinin orjinali üzerinden de sil inplace=true sayesinde

In [305]:
df

var1  var2  var3
b     7     8     8
c     2     5     8
d     5     0     6
e     5     1     1

In [306]:
l = ["var1","var2"]

In [307]:
df.drop(l, axis = 1)#fancy ile değişken sil. Tek tek değişkenlerin ismini yazarak drop yapmaya gerek kalmıyor.

var3
b     8
c     8
d     6
e     1

# Gözlem ve Değişken Seçimi: loc & iloc

In [323]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3)) #10'a 3'lük 'den 1 ile 30  arasındaki sayıları içeren 2 boyutlu bir array oluştur.
df = pd.DataFrame(m, columns = ["var1","var2","var3"]) #numpy array üzerinden dataframe oluştur, değişkenlere var1, var2 ve var3 ismini ver.
df

var1  var2  var3
0    26    11    12
1    12     6    21
2    25     7    19
3     9    14     6
4    18    28     3
5    27    21    16
6     7     8    27
7    15    29     2
8     8     7    16
9    27    26    13

In [324]:
#Komutun nasıl yazıldığını, argümanlarını unutursak komutun başına ? koyarak öğrenebiliriz.

In [325]:
?np.random.randint 

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.randint`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outpu

In [326]:
#loc: tanımlandığı şekli ile seçim yapmak için kullanılır.

In [327]:
df.loc[0:3] #veri setinin ilk halindeki indekslemeye sadık kalacak şekilde seçim imkanı veriyor. 3. indeksi dahil eder.

var1  var2  var3
0    26    11    12
1    12     6    21
2    25     7    19
3     9    14     6

In [328]:
#iloc: alışık olduğumuz indeksleme mantığı ile seçim yapar.

In [329]:
df.iloc[0:3]#burada 0'dan 3'e kadar seçim yapar. 3. indeksi almaz

var1  var2  var3
0    26    11    12
1    12     6    21
2    25     7    19

In [334]:
df[0:3]

var1  var2  var3
0    26    11    12
1    12     6    21
2    25     7    19

In [335]:
df.iloc[0:3, 0:2]

var1  var2
0    26    11
1    12     6
2    25     7

In [336]:
df.iloc[0,0] #0. satır 0. sütundaki değeri alır

26

In [337]:
df

var1  var2  var3
0    26    11    12
1    12     6    21
2    25     7    19
3     9    14     6
4    18    28     3
5    27    21    16
6     7     8    27
7    15    29     2
8     8     7    16
9    27    26    13

In [338]:
df.iloc[:3,:2] #3 satır ve 2 satır getirir

var1  var2
0    26    11
1    12     6
2    25     7

In [339]:
df.loc[0:3, "var3"] #0'dan 3'e kadar (3'ü dahil eder) var3 değişkenini getir.

0    12
1    21
2    19
3     6
Name: var3, dtype: int32

In [343]:
df.iloc[0:3]["var3"] #kullanım şekli loc'a göre farklıdır. Değişken ismi ayrı bir [] içine yazılır

0    12
1    21
2    19
Name: var3, dtype: int32

In [344]:
df[0:3]["var3"]

0    12
1    21
2    19
Name: var3, dtype: int32

# Koşullu Eleman İşlemleri

In [345]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    13    10    21
1    14    12    24
2    16     4    24
3     1    13    18
4     3     5    17
5     3    12     4
6     4     6    26
7    15    29     5
8     5    23    16
9    28    18    17

In [346]:
df["var1"] #df.var1 ile de aynı işlemi yapabiliriz

0    13
1    14
2    16
3     1
4     3
5     3
6     4
7    15
8     5
9    28
Name: var1, dtype: int32

In [347]:
df[0:2][["var1","var2"]]#2 köşeli parantez var yani fancy yardımıyla yapıyoruz.

var1  var2
0    13    10
1    14    12

In [348]:
df

var1  var2  var3
0    13    10    21
1    14    12    24
2    16     4    24
3     1    13    18
4     3     5    17
5     3    12     4
6     4     6    26
7    15    29     5
8     5    23    16
9    28    18    17

In [349]:
df.var1 #dataframe içerisinde var1'i seç demek

0    13
1    14
2    16
3     1
4     3
5     3
6     4
7    15
8     5
9    28
Name: var1, dtype: int32

In [350]:
df[df.var1 > 15]#dataframe içerisinde var1 değişkeninde 15'den büyük olanları ver

var1  var2  var3
2    16     4    24
9    28    18    17

In [351]:
df[(df.var1 > 15) & (df.var3 < 5)] #1'den fazla koşul girebilriz

Empty DataFrame
Columns: [var1, var2, var3]
Index: []

In [360]:
df[(df.var1 > 15), ["var1","var2"]]

InvalidIndexError: (0     True
1     True
2    False
3     True
4    False
5     True
6     True
7     True
8    False
9    False
Name: var1, dtype: bool, ['var1', 'var2'])

In [352]:
df.loc[(df.var1 > 15), ["var1","var2"]] #15'den büyük olanlarda var1 ve var2'yi seç. Eğer koşuldan sonra değişken seçmek istersek loc ekleyebiliriz

var1  var2
2    16     4
9    28    18

In [353]:
df[(df.var1 > 15)][["var1","var2"]] #diğer yolu da fancy indeks ile yapmak

var1  var2
2    16     4
9    28    18

# Birleştirme (Join) İşlemleri

In [354]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1","var2","var3"])#numpy array üzerinden dataframe oluştur
df1

var1  var2  var3
0     4    28    27
1     4    18    22
2    20    14     9
3    11    26    19
4     2    11     7

In [355]:
df2 = df1 + 99 #tüm değerlerinin üzerine 99 ekle ve başka bir dataframe'e ata

In [356]:
df2

var1  var2  var3
0   103   127   126
1   103   117   121
2   119   113   108
3   110   125   118
4   101   110   106

In [357]:
pd.concat([df1,df2])# 2 data frame'i alt alta birleştirir. Çıktıda indekslerin tekrarlandığına dikkat edelim.

var1  var2  var3
0     4    28    27
1     4    18    22
2    20    14     9
3    11    26    19
4     2    11     7
0   103   127   126
1   103   117   121
2   119   113   108
3   110   125   118
4   101   110   106

In [268]:
?pd.concat
#fonksiyon ile ilgili detay bilgi verir

Signature:
pd.concat(
    objs: 'Iterable[NDFrame] | Mapping[HashableT, NDFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool' = True,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised.
axis : {0/'index', 1/'col

In [358]:
pd.concat([df1,df2], ignore_index=True) # ignore_index'in ön tanımlı değeri false. Biz true yaparak bu sorunu hallettik.

var1  var2  var3
0     4    28    27
1     4    18    22
2    20    14     9
3    11    26    19
4     2    11     7
5   103   127   126
6   103   117   121
7   119   113   108
8   110   125   118
9   101   110   106

In [359]:
df1.columns #dataframe değişken isimlerine ulaşırız

Index(['var1', 'var2', 'var3'], dtype='object')

In [360]:
df2.columns = ["var1","var2","deg3"] #değişken isimlerini değiştiriyoruz

In [361]:
df2

var1  var2  deg3
0   103   127   126
1   103   117   121
2   119   113   108
3   110   125   118
4   101   110   106

In [362]:
df1

var1  var2  var3
0     4    28    27
1     4    18    22
2    20    14     9
3    11    26    19
4     2    11     7

In [363]:
pd.concat([df1, df2], ignore_index=True) #değişken isimlerinde farklılık olduğu için birleştirme işlemi sonucu 4 değişken oluşur.

var1  var2  var3   deg3
0     4    28  27.0    NaN
1     4    18  22.0    NaN
2    20    14   9.0    NaN
3    11    26  19.0    NaN
4     2    11   7.0    NaN
5   103   127   NaN  126.0
6   103   117   NaN  121.0
7   119   113   NaN  108.0
8   110   125   NaN  118.0
9   101   110   NaN  106.0

In [364]:
df3 = pd.concat([df1, df2], ignore_index=True);

In [365]:
df3[df2.columns] #df2 sütunlarına göre isimlendir.

var1  var2   deg3
0     4    28    NaN
1     4    18    NaN
2    20    14    NaN
3    11    26    NaN
4     2    11    NaN
5   103   127  126.0
6   103   117  121.0
7   119   113  108.0
8   110   125  118.0
9   101   110  106.0

In [366]:
pd.concat([df1, df2], join = "inner") #join argümanı inner olduğunda birleştirmeyi kesişimlerine göre birleştirdi.

var1  var2
0     4    28
1     4    18
2    20    14
3    11    26
4     2    11
0   103   127
1   103   117
2   119   113
3   110   125
4   101   110

# İleri Birleştirme İşlemleri

In [367]:
import pandas as pd

In [368]:
#birebir birlestirme

In [369]:
df1 = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                    'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'İK']})#bir sözlük üzerinden bir dataframe oluşturduk. Çalışanlar var ve çalışanların grupları yer alıyor

df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [370]:
df2 = pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'],
                    'ilk_giris': [2010, 2009, 2014, 2019]}) #ikinci dataframe yine sözlük üzerinden oluşturuldu.

df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [371]:
pd.merge(df1, df2) #birebir birleştirme yapar. Birleştirmelerin hangi değişkene göre yapılacağını kendisi anlıyor. İki verisetinde de çalışanlar olduğu için çalışanlara göre birleştirdi.

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [372]:
pd.merge(df1, df2, on = "calisanlar") #birleştirmeyi biz calisanlara göre yap diye bu şekilde de (on argümanı ile de) yapabiliriz.

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [373]:
#coktan teke (many to one)

In [374]:
df3 = pd.merge(df1, df2)

In [375]:
df3 #burada grup 4 elemandan oluşuyor (çok->bir değer birden fazla satırda)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [376]:
df4 = pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik', 'İK'],
                    'mudur': ['Caner', 'Mustafa', 'Berkcan']})

df4 #burada grup 3 elemandan oluşuyor (tek->bir değer tek satırda)

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [377]:
pd.merge(df3,df4) #çoktan teke birleştirme yaptı. grup ortak değişken olduğu için otomatik olarak gruba göre birleştirme yaptı

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

In [378]:
# çoktan çoka

In [379]:
df5 = pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe',
                              'Muhendislik', 'Muhendislik', 'İK', 'İK'],
                    'yetenekler': ['matematik', 'excel', 'kodlama', 'linux',
                               'excel', 'yonetim']})

df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [380]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [405]:
pd.merge(df1, df5) #bütün çalışanları çokladı

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           İK      excel
7      Fatma           İK    yonetim

# Toplulaştırma ve Gruplama (Aggregation & Grouping)****
Pandas'ın en önemli kısımlarından biridir.
Elimize bir veri seti geldiğinde, veri seti ile ilgili analizler yapmak istediğimizde kullanacağımız ilk özellikler buradakiler olacaktır.

Basit toplulaştırma fonksiyonları:

* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [381]:
import seaborn as sns #seaborn kütüphanesi içerisinde bazı veri setleri var. seaborn veri setini sns ismiyle import ediyoruz.

In [408]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed thr

In [382]:
df = sns.load_dataset("planets") #planets veri setini yükler.
df.head()#veri setini baştan görüntüleyelim

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [383]:
df.shape #Bu veri seti (1035,6) boyutunda yani 1035 gözlem (satır) ve 6 değişkenden (sütun) oluşuyormuş.

(1035, 6)

In [384]:
df.mean()  #bütün değişkenlerin ortalama değerlerini verir.

C:\Users\Fatma Zehra\AppData\Local\Temp\ipykernel_15140\1543727390.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()  #bütün değişkenlerin ortalama değerlerini verir.


number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [385]:
df["mass"].mean() #mass değişkenine ait ortalamayı verir. Önce değişkeni seçiyoruz sonra ona ortalama alma fonksiyonunu bağlıyoruz.

2.6381605847953216

In [386]:
df["mass"].count() #mass içerisindeki değerleri saymak için kullanılır

513

In [387]:
df["mass"].min() #mass içerisindeki minimum değeri döndürür.

0.0036

In [388]:
df["mass"].max()  #mass içerisindeki maksimum değeri döndürür.

25.0

In [389]:
df["mass"].sum()  #mass içerisindeki değerleri toplar

1353.37638

In [390]:
df["mass"].std() #mass içerisindeki değerlere ait standart sapmayı hesaplar

3.8186166509616046

In [391]:
df["mass"].var() #mass içerisindeki değerlere ait standart varyansı hesaplar

14.58183312700122

In [392]:
df.describe() #bütün değişkenler için temel betimsel istatistiksel özelliklerini ortaya koyar

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [393]:
df.describe().T #transpozunu alır (satırları sütun, sütunları satır yapar)

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [394]:
df.dropna().describe().T #eğer elimizdeki veri seti içerisinde eksik değerler olursa ki bu çok karşılaşılan bir durumdur fakat yine de istatistiksel özelliklerine bakmak istersek dropna fonksiyonu ile eksik gözlemleri silerek sonuna yine describe ekleyerek temel istatistiksel özellikleri öğrenebiliriz.

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

# Gruplama İşlemleri

In [395]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'veri': [10,11,52,23,43,55]}, columns=['gruplar', 'veri']) #böyle bir dataframe oluşturlaım sözlük üzerinden
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [396]:
#gruplama işlemi veri setinde yer alan kategorik değişkenlerin gruplarının yakalanması ve bu grupların özelinde bazı işlemler yapılması demek

In [397]:
df.groupby("gruplar") #Dataframe'e git groupby fonksiyonu ile gruplar değişkenlerini yakala bu gruplar değişkeninin içerisinde yer alan kategori sınıflarını tut. Yani A'yı tuttu, B'yi tuttu, C'yi tuttu.

In [398]:
#groupby fonksiyonu kendinden sonra toplulaştırma (aggregation) fonksiyonu ister.

In [399]:
df.groupby("gruplar").mean() #grupların ortalamasını alır. Grupları yakladık fakat ne´yapacağını belirtmemiz gerekiyor.

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [400]:
df.groupby("gruplar").sum() #grupların içerisindeki değerlerin toplamını verir.

veri
gruplar      
A          33
B          54
C         107

In [401]:
df = sns.load_dataset("planets") #planets veri setini yükleyelim
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [402]:
df.groupby("method") #method isimli kategorik değişkeni yakalayalım. groupby fonksiyonu kategorik değişkenler üzerinde çalışır.

In [403]:
df.groupby("method")["orbital_period"].mean() #toplulaştırma yapacağımız değişkeni de seçiyoruz (orbital_period) ve toplulaştırma yöntemlerinden olan mean()'ı kullanalım.
                                              #bu gruplara karşılık gelen orbital_period değişkenini yakaladık.
    #Önceki örnekte tek değişken olduğu için değişken belirtmeden toplulaştırma fonksiyonlarını kullnabilmiştik. Fakat burada çok fazla değişken olduğu için gruplar bazında hangi değişkeni de kullanmamız gerektiğini belirtmemiz grekiyor.

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [404]:
#Bir önceki örnekte grup dışında tek bir değişken vardı (veri) bu nedenle değişken ismini belirtmemiştik. Bu örnekte çok değişken olduğu için gruplama yaptıktan sonra toplulaştırma yapacağımız değişkeni de belirtmemiz gerekiyor

In [405]:
df.groupby("method")["orbital_period"].describe() #Gruplara denk gelen orbital_period değişkenine ait temel istatistiksel özelliklerini ver

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

# İleri Toplulaştırma İşlemleri (Aggregate, filter, transform, apply)
Bu fonksiyonlar bizim için hayati öneme sahip. 

In [406]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2']) #sözlük üzerinden bir dataframe tanımlayalım.
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [407]:
#aggregate

In [408]:
df.groupby("gruplar").mean() #grupları yakaladık ve her gruba denk gelen hem değişken1 hem değişken 2 için mean işlemini yapar.

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [409]:
df.groupby("gruplar").aggregate([min, np.median, max]) # birden fazla toplulaştırma fonksiyonu kullanabiliriz. min, median ve max işlemlerini yapmak isteyelim.
                                                       #Bunun gibi durumlarda aggregate fonksiyonu işimizi görecektir.
                                                       #np.median dışarıdan bir fonksiyon çağırıyoruz.min ve max pandas içinde olduğu için direk kullandık.
                                                        #istediğimiz özellikleri aggregate ile getirebiliriz. min ve max 'ı tırnak içine de alabiliriz çalışır. "min", "max" olabilir.

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   16.0  22       100  181.0  262
B              11   17.0  23       111  182.0  253
C              33   66.0  99       333  651.0  969

In [410]:
df.groupby("gruplar")["degisken1"].aggregate([min, np.median, max])

min  median  max
gruplar                  
A         10    16.0   22
B         11    17.0   23
C         33    66.0   99

In [411]:
df.groupby("gruplar").aggregate({"degisken1": min, "degisken2": "max"}) # gruplara ait degisken1 değerleri için minimumu hesapla, değişken2 değerlei için maksimumu hesapla.
                                                                        # 2 değişken için de 2 farklı istatistik hesapladık
                                                                        #min ifadesini de tırnak içerisinde yazabiliriz veya max ifadesini tırnak dışına çıkarabiliriz

degisken1  degisken2
gruplar                      
A               10        262
B               11        253
C               33        969

In [456]:
#filter

In [412]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2']) #sözlük üzerinden dataframe oluşturduk
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [413]:
#Pandasın sunduğu özelliklerden daha farklı daha karmaşık bir özellik istiyoruz. 
#Bu durumda kendi kişisel fonksiyonlarımızı değişkenler üzerinde filtreleme aracı olarak kullanabiliriz

In [414]:
def filter_func(x):
    return x["degisken1"].std() > 9 #fonksiyon tanımladık

In [415]:
df.groupby("gruplar").std() #gruplama yaparak değişkenlere ait std'leri hesapladık

degisken1   degisken2
gruplar                       
A         8.485281  114.551299
B         8.485281  100.409163
C        46.669048  449.719913

In [416]:
df.groupby("gruplar").filter(filter_func)#filter fonksiyon bekler. Fonksiyonda belirlediğimiz şekilde filtreleme yaptık

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

In [417]:
df.groupby("gruplar").filter(lambda x: x["degisken1"].std() > 9) #isimsiz fonksiyon şeklinde de yazabiliriz

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

In [418]:
#transform
#verisetinin değişkenleri üzerinde işlemler yapmak onları farklı değerlere dönüştürmek istiyoruz ve bu dönüştürme işlemini kendimiz tanımlamak istiyoruz

In [419]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [420]:
df["degisken1"]*9 #Pandas ta her bir değişken1 değerini 9 ile çarp

0     90
1    207
2    297
3    198
4     99
5    891
Name: degisken1, dtype: int64

In [421]:
df[:][["degisken1","degisken2"]]

degisken1  degisken2
0         10        100
1         23        253
2         33        333
3         22        262
4         11        111
5         99        969

In [422]:
df_a =df[:][["degisken1","degisken2"]]

In [423]:
df_a = df.iloc[:,1:3] #tüm satırları ve 1 ve 2. satırları yani (değişken1 ve değişken2) seç, aslında kateborik değişken olan grupları dataframe'den çıkarmış olduk

In [424]:
df_a

degisken1  degisken2
0         10        100
1         23        253
2         33        333
3         22        262
4         11        111
5         99        969

In [425]:
df_a.transform(lambda x: (x-x.mean()) / x.std()) #kendi tanımladığımız bir isimsiz fonksiyonu değişkenler üzerinde gezdirebiliyoruz. her bir değişkenin değerinden değişken ortalamasını çıkaralım elde ettiğimiz sonucu değişken standart sapmasına bölelim.
                                                 #aslında bu işlem standart normalizasyondur.
    
#transform fonksiyonunun özelliği bizim tanımlayacağımız fonksiyonu değişkenler üzerine uygulamak.

degisken1  degisken2
0  -0.687871  -0.738461
1  -0.299074  -0.263736
2   0.000000  -0.015514
3  -0.328982  -0.235811
4  -0.657963  -0.704331
5   1.973890   1.957853

In [426]:
#apply
#tıpki filter ve transfom fonkisyonu gibi dataframe değişkenleri üzerinde gezebilme ve toplulaştırıcı işlem yapma olanağı sağlayan fonksiyondur.

In [427]:
import pandas as pd
df = pd.DataFrame({'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['degisken1', 'degisken2'])
df

degisken1  degisken2
0         10        100
1         23        253
2         33        333
3         22        262
4         11        111
5         99        969

In [428]:
df.apply(np.sum) # numpy'ın sum fonksiyonunu çağırdık.

degisken1     198
degisken2    2028
dtype: int64

In [429]:
df.apply(np.mean)

degisken1     33.0
degisken2    338.0
dtype: float64

In [430]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [431]:
df.groupby("gruplar").apply(np.sum) #gruplama yap gruplardaki her bir sınıfa apply fonksiyonunu uygula

gruplar  degisken1  degisken2
gruplar                              
A            AA         32        362
B            BB         34        364
C            CC        132       1302

In [432]:
df.groupby("gruplar").sum()

degisken1  degisken2
gruplar                      
A               32        362
B               34        364
C              132       1302

# Pivot Tablolar
Veri setleri üzerinde bazı satır ve sütun işlemleri yaparak veri setlerini istenilen hale getirmek için kullanılan tablolardır.

In [433]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic') #titanic veri setini yükledik
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [434]:
titanic.groupby("sex")["survived"].mean() #cinsiyete göre verileri gruplayıp survived değişkeninin ortalamasını al

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [435]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [436]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean") #iki kategorik değişkenin kesişimlerine göre grupla ve survived değişkenlerinin ortalamasını al

survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [437]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack() #Aslında pandas içerisindeki klasik yaklaşımlar ile pivot tablo oluşturduk

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
#pivot ile table

In [438]:
titanic.pivot_table("survived", index = "sex", columns = "class") #odaklandığımız değişken survivor, indeksi cinsiyet başka hangi değişkene odaklanalım class
                                                                  #indeks olarak girdiğimiz yeri tabloda satır olarak aldı, columns olarak giridğimizi sütunlara koydu

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [439]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [440]:
age = pd.cut(titanic["age"], [0, 18, 90]) #sürekli değişkeni kategorik değişkene çevirdik, titanik verisi içerisindeki age değişkenini aralıklar vererek böl.
age.head(10) #ilk 10 gözlemi inceleyelim
#sürekli bir değişken olan age değişkenini kategorik değişkene çeviridk bu kategorik değişkenin de 3 sınıfı oldu

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [442]:
titanic.pivot_table("survived", ["sex", age], "class") #survived değişkenine odaklan,  satır olarak sex ve age değişkenine , sütun olarak class değişkenine odaklan
                                                    #age dışarıdan gelen kendi tanımladığımız bir değişken olduğu için "" içine yazmadık

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

In [444]:
titanic.pivot_table("survived", ["sex", age], "class", aggfunc='sum') #ön tanımlı aggregate fonksiyonu mean'dır

class            First  Second  Third
sex    age                           
female (0, 18]      10      14     22
       (18, 90]     72      54     25
male   (0, 18]       4       9     11
       (18, 90]     36       6     27

# Dış Kaynaklı Veri Okumak

In [1]:
import pandas as pd

In [6]:
?pd.read_csv

Signature:
pd.read_csv(
    filepath_or_buffer,
    sep=',',
    delimiter=None,
    header='infer',
    names=None,
    index_col=None,
    usecols=None,
    squeeze=False,
    prefix=None,
    mangle_dupe_cols=True,
    dtype=None,
    engine=None,
    converters=None,
    true_values=None,
    false_values=None,
    skipinitialspace=False,
    skiprows=None,
    skipfooter=0,
    nrows=None,
    na_values=None,
    keep_default_na=True,
    na_filter=True,
    verbose=False,
    skip_blank_lines=True,
    parse_dates=False,
    infer_datetime_format=False,
    keep_date_col=False,
    date_parser=None,
    dayfirst=False,
    iterator=False,
    chunksize=None,
    compression='infer',
    thousands=None,
    decimal=b'.',
    lineterminator=None,
    quotechar='"',
    quoting=0,
    doublequote=True,
    escapechar=None,
    comment=None,
    encoding=None,
    dialect=None,
    tupleize_cols=None,
    error_bad_lines=True,
    warn_bad_lines=True,
    delim_whitespace=False,
    

In [1]:
pd.read_csv("reading_data/ornekcsv.csv")

NameError: name 'pd' is not defined

In [521]:
#csv okuma
pd.read_csv("reading_data/ornekcsv.csv", sep = ";")# ilk argüman okunmak istenen dosyanın konumunu ifade ediyor, ikinci argüman olarak ayracı belirttik. sep ön tanımlı argümanı , dür 

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [523]:
#txt okuma
pd.read_csv("reading_data/duz_metin.txt") #read_csv ile txt'de okuyabiliriz. fonksiyonun ayraç olarak ön tanımlı değeri virgül ama txtdeki ayraç boşluk olduğu halde yine de okuyabildi.
                                          #düz metinlerde ayraç olarak boşluk varsa read_csv fonksiyonu görebilir.

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [524]:
#excel
pd.read_excel("reading_data/ornekx.xlsx") #excel dosyası okuma

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [413]:
df = pd.read_excel("reading_data/ornekx.xlsx") #excel'den okuduğumuzu bir dataframe'e atadık

In [414]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.head()

a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [415]:
df.columns = ("A","B","C") #değişkenlere yeniden isimler verdik

In [13]:
df

A    B     C
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [417]:
#sıfırdan txt okuma
tips = pd.read_csv("reading_data/data.txt")

In [418]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv')
data.head()

NameError: name 'pd' is not defined

# Bonus: Problem Çözme ve Döküman Okuma Kültürü

# BOLUM SONU DEGERLENDIRMESI